services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: ["npm", "run", "dev"]
    networks:
      - aemios-network

  babylon:
    build:
      context: .
      dockerfile: docker/babylon.Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./babylon:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: ["npm", "run", "dev"]
    networks:
      - aemios-network

networks:
  aemios-network:
    driver: bridge